common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0
    serials : "933"
    port : 8554
    resolution : 12
    fov : 4
    opt_frame_fn : 6 #frame number which will be optimized in front-end
    opt_num_in_one_frame : 20 #how many times you want to optimize in one frame
    backend_opt_pose_num: 20

preprocess:
    lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 6
    blind: 4

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    90
    det_range:     450.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
    extrinsic_T: [ 0.04165, 0.02326, -0.0284 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]
    cam_lidar_ext: [-0.040507, -0.998998, -0.019029, 0.163793,
                     0.0388064, 0.0174573, -0.999094, 0.0762877, 
                     0.998425, -0.0412087, 0.0380603, -0.438607, 
                     0, 0, 0, 1]
    cam_intrinsic: [817.846, 0, 1000.37, 
                    0, 835.075, 551.246, 
                    0, 0, 1]

publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame
    frame_num_to_stop: 100000
    frame_map_to_save: 200
    rgb_point_save_num: 200000

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

